# @baseUrl = http://localhost:3000
@baseUrl = https://chatapp-api-ecru.vercel.app

### ------------------- SYSTEM ROUTES -------------------

### Vercel Test Endpoint
GET {{baseUrl}}/api/test
Content-Type: application/json

### ------------------- AUTH ROUTES -------------------

# @name signup
POST {{baseUrl}}/signup
Content-Type: application/json

{
    "email": "amroaltayeb14@gmail.com",
    "name": "Amro Altyeb",
    "password": "amro123"
}

### Verify Email
# Note: You need the token from the email (or database/console if logging)
POST {{baseUrl}}/verify-email
Content-Type: application/json

{
    "verificationToken": "12345678"
}

# @name login
POST {{baseUrl}}/signin
Content-Type: application/json

{
    "email": "amroaltayeb14@gmail.com",
    "password": "amro123"
}

### Check Auth (Verify if logged in)
GET {{baseUrl}}/check-auth
Content-Type: application/json

### Logout
POST {{baseUrl}}/logout
Content-Type: application/json

### Get All Users (Admin)
GET {{baseUrl}}/getall
Content-Type: application/json

### Forgot Password
POST {{baseUrl}}/forgot-password
Content-Type: application/json

{
    "email": "amroaltayeb14@gmail.com"
}

### Reset Password
# Replace :resetCode with the token received in email
POST {{baseUrl}}/reset-password/your_reset_token_here
Content-Type: application/json

{
    "password": "newpassword123"
}

### Onboarding (Complete Profile)
POST {{baseUrl}}/onboarding
Content-Type: application/json

{
    "profilePic": "https://avatar.iran.liara.run/public/1",
    "bio": "I love coding and video calls!",
    "location": "San Francisco",
    "gender": "male"
}

### Delete User
DELETE {{baseUrl}}/delete/user_id_here
Content-Type: application/json


### ------------------- USER ROUTES -------------------

### Get Suggested Friends
GET {{baseUrl}}/user/suggested
Content-Type: application/json

### Get User Profile
GET {{baseUrl}}/user/profile/user_id_here
Content-Type: application/json

### Get Friends List
GET {{baseUrl}}/user/friends/user_id_here
Content-Type: application/json

### Send Friend Request
POST {{baseUrl}}/user/send-friend-request/receiver_id_here
Content-Type: application/json

### Get Incoming Friend Requests
GET {{baseUrl}}/user/get-friends-request
Content-Type: application/json

### Accept Friend Request
# Replace :id with the Friend Request ID (not User ID)
POST {{baseUrl}}/user/accept-friend-request/request_id_here
Content-Type: application/json

### Get Outgoing Friend Requests
GET {{baseUrl}}/user/get-outgoing-friend-requests
Content-Type: application/json

### Get All Friend Requests (Admin)
GET {{baseUrl}}/user/get-all-friend-requests
Content-Type: application/json


### ------------------- CHAT ROUTES -------------------

### Get Stream Token
GET {{baseUrl}}/chat/token
Content-Type: application/json
